<?php

namespace Database\Seeders;

use App\Models\Category;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            [
                'pattern' => 'Halo',
                'topic' =>  '',
                'that' => '',
                'template' => '<random><li>Halo ada yang bisa dibantu?</li><li>Halo juga, silakan bertanya</li><li>Halo dengan siapa kita berbicara?</li><li>Halo kamu angkatan tahun berapa?</li><li>Halo bagimana kondisimu hari ini?</li></random>',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'aku *',
                'topic' =>  '',
                'that' => '',
                'template' => 'Halo! <set name = "username"> <star/></set>, Ada yang bisa dibantu?',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '^ angkatan *',
                'topic' =>  '',
                'that' => '',
                'template' => 'Tahun angkatan mu telah berhasil disimpan <think> <set name = "year"> <star/></set></think>',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '^ jurusan *',
                'topic' =>  '',
                'that' => '',
                'template' => 'Jurusan kamu telah berhasil disimpan <think> <set name = "major"> <star/></set></think>',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '^ Terima Kasih ^',
                'topic' =>  '',
                'that' => '',
                'template' => 'Halo <get name = "username"/>, Sama-sama',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'Info diri',
                'topic' =>  '',
                'that' => '',
                'template' => 'Nama <get name = "username"/>, Tahun <get name = "year"/>, Jurusan <get name = "major"/>',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '* tahun lulus *',
                'topic' =>  '',
                'that' => '',
                'template' => 'Halo <star index="1"/> dengan tahun kelulusan <star index="2"/>',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'Bagaimana cuaca hari ini',
                'topic' =>  '',
                'that' => '',
                'template' => '<think><set name = "state"> cerah</set></think><condition name = "state" value = "cerah">Cuaca hari ini di Untar sangat cerah</condition><condition name = "state" value = "hujan">Cuaca hari ini di Untar sedang tidak baik</condition>',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '^ BPP ^',
                'topic' =>  '',
                'that' => '',
                'template' => 'Apakah kamu ingin tahu harga bpp? (iya/tidak)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'iya',
                'topic' =>  '',
                'that' => 'Apakah kamu ingin tahu harga bpp? (iya/tidak)',
                'template' => 'Harga BPP Untuk Angkatan 2017 = Rp. 5.000.000, Angkatan 2018 = Rp. 5.500.000, Angkatan 2019 = Rp. 6.000.000.',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'tidak',
                'topic' =>  '',
                'that' => ' Apakah kamu ingin tahu harga bpp? (iya/tidak)',
                'template' => 'Apakah kamu ingin tahu kapan harus membayar bpp? (iya/tidak)',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'iya',
                'topic' =>  '',
                'that' => 'Apakah kamu ingin tahu kapan harus membayar bpp? (iya/tidak)',
                'template' => 'BPP harus dilunasi sebelum kamu mengisi KRRS',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'tidak',
                'topic' =>  '',
                'that' => 'Apakah kamu ingin tahu kapan harus membayar bpp? (iya/tidak)',
                'template' => 'Baik, terima kasih',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'Wisuda',
                'topic' =>  '',
                'that' => '',
                'template' => 'Halo, Info mengenai Wisuda dapat dilihat pada link berikut ya : https://lintar.untar.ac.id/ltrmhz/wisuda/wis_info.aspx',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '^ Wisuda *',
                'topic' =>  '',
                'that' => '',
                'template' => '<srai>Munculkan info Kelulusan di <star/></srai>',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'Munculkan info Kelulusan di untar',
                'topic' =>  '',
                'that' => '',
                'template' => 'Halo, Info mengenai Wisuda dapat dilihat pada link berikut ya : https://lintar.untar.ac.id/ltrmhz/wisuda/wis_info.aspx',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'Siapa Dekan *',
                'topic' =>  '',
                'that' => '',
                'template' => '<srai>Dekan <star/> sekarang</srai>',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'Dekan FTI sekarang',
                'topic' =>  '',
                'that' => '',
                'template' => 'Dekan FTI Untar saat ini adalah Prof. Dr. Dyah Erny Herwindiati',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'Dekan FH sekarang',
                'topic' =>  '',
                'that' => '',
                'template' => 'Dekan FH Untar saat ini adalah Prof. Dr. Amad Sudiro',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '^ Ruang Dosen ^',
                'topic' =>  '',
                'that' => '',
                'template' => 'Halo, Ruang Dosen FTI terletak di Lantai 10 Gedung R ya !',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '* Ruang Kesekretariatan ^',
                'topic' =>  '',
                'that' => '',
                'template' => 'Halo, Ruang Kesekretariatan terletak di Lantai 7 Gedung R ya !',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '^ KRRS ^',
                'topic' =>  '',
                'that' => '',
                'template' => 'Halo, Untuk Mengisi KRRS dapat dilakukan pada link berikut ya : https://lintar.untar.ac.id/ltrmhz/skpi_new/skpi_main.aspx',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '^ Alamat * Untar',
                'topic' =>  '',
                'that' => '',
                'template' => '<srai>Lokasi <star/></srai>',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'Lokasi FTI',
                'topic' =>  '',
                'that' => '',
                'template' => 'Alamat Fakultas Teknologi Informasi Universitas Tarumanagara adalah Jl. Letjen S. Parman No. 1 Jakarta Barat 11440, Indonesia Gedung R Lantai 11',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => 'Lokasi Fakultas Teknologi Informasi',
                'topic' =>  '',
                'that' => '',
                'template' => 'Alamat Fakultas Teknologi Informasi Universitas Tarumanagara adalah Jl. Letjen S. Parman No. 1 Jakarta Barat 11440, Indonesia Gedung R Lantai 11',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '^ beasiswa ^',
                'topic' =>  '',
                'that' => '',
                'template' => 'Halo, untuk mendapatkan beasiswa, isi dulu yuk biodata pada link berikut : https://lintar.untar.ac.id/ltrmhz/beasiswa/bea_biobeasiswa.aspx',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '^ Jadwal Kuliah ^',
                'topic' =>  '',
                'that' => '',
                'template' => 'Halo, untuk melihat jadwal kuliah, anda bisa melihatnya pada link berikut : https://lintar.untar.ac.id/ltrmhz/akademik/jadwal.aspx',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'pattern' => '^ Cuti ^',
                'topic' =>  '',
                'that' => '',
                'template' => 'Halo, untuk cuti akademik, anda bisa mengisi formulir pada link berikut : https://lintar.untar.ac.id/ltrmhz/cutiol/cutiol_ajuan.aspx',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ];

        foreach ($categories as $category) {
            Category::Create($category);
        }
    }
}
